# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encurtar',
            name='url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
