# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encurtar', '0002_encurtar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', max_length=500)),
                ('shorturl', models.URLField(default='', max_length=500)),
                ('hint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Encurtar',
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encurtar.User'),
        ),
    ]
