# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encurtar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
