# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encurtar', '0002_auto_20160219_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='shorturl',
            new_name='shortUrl',
        ),
    ]
