# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtar', '0003_auto_20160219_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortUrl',
            field=models.URLField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(default='', unique=True),
        ),
    ]
