# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encurtar', '0004_auto_20160219_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='hint',
            new_name='hits',
        ),
    ]
